src/Entity/Joueur.php
<?php

namespace App\Entity;

use App\Repository\JoueurRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JoueurRepository::class)
 */
class Joueur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_joueur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_joueur;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getNomJoueur(): ?string
    {
        return $this->nom_joueur;
    }

    public function setNomJoueur(string $nom_joueur): self
    {
        $this->nom_joueur = $nom_joueur;

        return $this;
    }

    public function getPrenomJoueur(): ?string
    {
        return $this->prenom_joueur;
    }

    public function setPrenomJoueur(string $prenom_joueur): self
    {
        $this->prenom_joueur = $prenom_joueur;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }
}

src/Form/JoueurType.php
<?php

namespace App\Form;

use App\Entity\Joueur;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class JoueurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_joueur',TextType::class,[
                'label'=>'Nom Joueur',
                'attr'=>[
                    'placeholder'=>'Nom du joueur',
                    'class'=>'Lastname'
                ]
            ])
            ->add('prenom_joueur',TextType::class, [
                    'label'=>'Prénom Joueur',
                    'attr'=>[
                        'placeholder'=>'Prénom du joueur',
                        'class'=>'Firstname'
                    ]
                ])
            ->add('age',TextType::class, [
                    'label'=>'Age Joueur',
                    'attr'=>[
                        'placeholder'=>'Age du joueur',
                        'class'=>'age'
                    ]
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Joueur::class,
        ]);
    }
}

src/Controller/JoueurController.php
<?php

namespace App\Controller;

use App\Entity\Joueur;
use App\Form\JoueurType;
use App\Repository\JoueurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;


class JoueurController extends AbstractController
{
    /**
     * @Route("/joueur", name="joueur")
     */
    public function index(): Response
    {
        return $this->render('joueur/index.html.twig', [
            'controller_name' => 'JoueurController',
        ]);
    }

    /**
     * @param JoueurRepository $repository
     * @return Response
     * @route("/AfficheJ", name="AfficheJoueur")
     */
    public function Affiche(JoueurRepository $repository){
        $joueur=$repository->findAll();
        return $this->render('joueur/Affiche.html.twig',
            ['joueur'=>$joueur]);
    }

    /**
     * @route("/delete/{id}",name="delete")
     */
    function Delete_joueur($id,JoueurRepository $repository){
        $joueur=$repository->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($joueur);
        $em->flush();
        return $this->redirectToRoute('AfficheJoueur');
    }

    /**
     * @param Request $request
     * @return Response
     * @route("joueur/ajouter")
     */
    function Ajouter_joueur(Request $request){
        $joueur = new Joueur();
        $form=$this->createForm(JoueurType::class,$joueur);
        $form->add('ajouter',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($joueur);
            $em->flush();
            return  $this->redirectToRoute('AfficheJoueur');
        }
        return $this->render('joueur/Ajouter.html.twig',[
           'form'=>$form->createView()
        ]);
    }
    /**
     * @route ("joueur/update/{id}",name="update")
     */
    function Update(JoueurRepository  $repository,$id,Request $request){
        $joueur=$repository->find($id);
        $form=$this->createForm(JoueurType::class,$joueur);
        $form->add('Update',SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("AfficheJoueur");
        }
        return $this->render('joueur/Update.html.twig',[
            'form'=>$form->createView()
        ]);
    }
}

templates/joueur/Affiche.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Liste des Joueur</h1>
<table border="3">
    <tr>
        <th>ID</th>
        <th>Nom Joueur</th>
        <th>Prenom Joueur</th>
        <th>Age</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    <tr {% for j in joueur %}>
        <td>{{ j.id }}</td>
        <td>{{ j.nomJoueur }}</td>
        <td>{{ j.prenomJoueur }}</td>
        <td>{{ j.age }}</td>
        <td><a href="{{ path('update',{'id':j.id}) }}">Update</a></td>
        <td><a href="{{ path('delete',{'id':j.id}) }}">Delete</a></td>
    </tr {% endfor %}>
</table>
</body>
</html>

templates/joueur/Ajouter.html.twig
<h1>Ajout Joueur</h1>
{{ form_start(form) }}
{{ form_end(form) }}

templates/joueur/Update.html.twig
<h1>Update Joueur</h1>
{{ form(form) }}

templates/joueur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JoueurController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/VolcanoFootball/src/Controller/JoueurController.php'|file_link(0) }}">src/Controller/JoueurController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/VolcanoFootball/templates/joueur/index.html.twig'|file_link(0) }}">templates/joueur/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}