src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EquipeRepository::class)
 */
class Equipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_equipe;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $drapeau_equipe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEquipe(): ?string
    {
        return $this->nom_equipe;
    }

    public function setNomEquipe(string $nom_equipe): self
    {
        $this->nom_equipe = $nom_equipe;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDrapeauEquipe(): ?string
    {
        return $this->drapeau_equipe;
    }

    public function setDrapeauEquipe(?string $drapeau_equipe): self
    {
        $this->drapeau_equipe = $drapeau_equipe;

        return $this;
    }


}

src/Form/EquipeType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EquipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_equipe',TextType::class,[
                'label'=>'Nom Equipe',
                'attr'=>[
                    'placeholder'=>'Nom du Equipe',
                    'class'=>'nom'
                ]
            ])
            ->add('date_creation',DateType::class, [
                'label'=>'Date Creation',
                'attr'=>[
                    'placeholder'=>'Date Creation',
                    'class'=>'date'
                ]
            ])
            ->add('drapeau_equipe',FileType::class, [
                'label'=>'Darapeau Equipe',
                'attr'=>[
                    'placeholder'=>'Drapeau Equipe',
                    'class'=>'drapeau'
                ],
                'mapped'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/EquipeController.php
<?php

namespace App\Controller;

use App\Entity\Equipe;
use App\Form\EquipeType;
use App\Repository\EquipeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EquipeController extends AbstractController
{
    /**
     * @Route("/equipe", name="equipe")
     */
    public function index(): Response
    {
        return $this->render('equipe/index.html.twig', [
            'controller_name' => 'EquipeController',
        ]);
    }

    /**
     * @param EquipeRepository $repository
     * @return Response
     * @route("/AfficheE", name="AfficheEquipe")
     */
    public function Affiche(EquipeRepository $repository){
        $equipe=$repository->findAll();
        return $this->render('equipe/Affiche.html.twig',
            ['equipe'=>$equipe]);
    }

    /**
     * @route("/delete/{id}",name="supprimer")
     */
    function Delete_joueur($id,EquipeRepository $repository){
        $equipe=$repository->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($equipe);
        $em->flush();
        return $this->redirectToRoute('AfficheEquipe');
    }

    /**
     * @param Request $request
     * @return Response
     * @route("equipe/ajouter")
     */
    function Ajouter_equipe(Request $request){
        $equipe = new Equipe();
        $form=$this->createForm(EquipeType::class,$equipe);
        $form->add('ajouter',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($equipe);
            $em->flush();
            return  $this->redirectToRoute('AfficheEquipe');
        }
        return $this->render('equipe/Ajouter.html.twig',[
            'form'=>$form->createView()
        ]);
    }
    /**
     * @route ("equipe/update/{id}",name="modifier")
     */
    function Update(EquipeRepository  $repository,$id,Request $request){
        $equipe=$repository->find($id);
        $form=$this->createForm(EquipeType::class,$equipe);
        $form->add('Update',SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("AfficheEquipe");
        }
        return $this->render('equipe/Update.html.twig',[
            'form'=>$form->createView()
        ]);
    }
}

templates/equipe/Affiche.html.twig
{% extends 'base-back.html.twig' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Liste Des Equipes</h4>
                <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom Equipe</th>
                        <th>Prenom Equipe</th>
                        <th>Drapeau Equipe</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr {% for e in equipe %}>
                        <td>{{ e.id }}</td>
                        <td>{{ e.nomEquipe }}</td>
                        <td>{{ e.dateCreation|date('d-m-Y') }}</td>
                        <td><img src="{{asset(e.drapeauEquipe)}}"/></td>
                        <td><a href="{{ path('modifier',{'id':e.id}) }}">Update</a></td>
                        <td><a href="{{ path('supprimer',{'id':e.id}) }}">Delete</a></td>
                    </tr {% endfor %}>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
{% endblock %}

templates/equipe/Ajouter.html.twig
{% extends 'base-back.html.twig' %}
{% block content %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {{ form_start(form) }}
                    <div class="form-group row">
                        <label for="example-text-input" class="col-md-2 col-form-label">{{ form_label(form.nom_equipe) }}</label>
                        <div class="col-md-10">
                            <input class="form-control" {{ form_widget(form.nom_equipe) }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-date-input" class="col-md-2 col-form-label">{{ form_label(form.date_creation) }}</label>
                        <div class="col-md-10">
                            <input class="form-control"  {{ form_widget(form.date_creation) }}>
                        </div>
                    </div>



                    {{ form_widget(form.date_creation) }}
                    {{ form_label(form.drapeau_equipe) }}
                    {{ form_widget(form.drapeau_equipe) }}
                {{ form_end(form) }}
            </div>
        </div> <!-- end col -->
    </div>
</div>
{% endblock %}

templates/equipe/Update.html.twig
<h1>Update Equipe</h1>
{{ form(form) }}

templates/equipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/VolcanoFootball/src/Controller/EquipeController.php'|file_link(0) }}">src/Controller/EquipeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/VolcanoFootball/templates/equipe/index.html.twig'|file_link(0) }}">templates/equipe/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}