src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $idMatch;

    /**
     * @ORM\Column(type="integer")
     */
    private $idArtiste;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomMatch;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomEvent;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMatch(): ?int
    {
        return $this->idMatch;
    }

    public function setIdMatch(int $idMatch): self
    {
        $this->idMatch = $idMatch;

        return $this;
    }

    public function getIdArtiste(): ?int
    {
        return $this->idArtiste;
    }

    public function setIdArtiste(int $idArtiste): self
    {
        $this->idArtiste = $idArtiste;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNomMatch(): ?string
    {
        return $this->nomMatch;
    }

    public function setNomMatch(string $nomMatch): self
    {
        $this->nomMatch = $nomMatch;

        return $this;
    }

    public function getNomEvent(): ?string
    {
        return $this->NomEvent;
    }

    public function setNomEvent(string $NomEvent): self
    {
        $this->NomEvent = $NomEvent;

        return $this;
    }
}

src/Entity/Matche.php
<?php
namespace App\Entity;

use App\Repository\MatcheRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MatcheRepository::class)
 */
class Matche
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Nom Arbitre is required")
     * *@Assert\Length(
     *    min = 4,
     *     max =20,
     *     minMessage = "Le nom d'un Arbitre doit comporter au moins {{ limit }} caractéres",
     *      minMessage = "Le nom d'un Arbitre doit comporter au plus {{ limit }} caractéres"
     *     )
     */
    private $NomArbitre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Tour is required")
     */
    private $tour;


    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity=Billet::class, mappedBy="matche",cascade={"all"}, orphanRemoval=true)
     */
    private $billets;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="NomMatche is required")
     * @Assert\Length(
     *    min = 10,
     *     max =50,
     *     minMessage = "Le nom d'un Nom Matche doit comporter au moins {{ limit }} caractéres",
     *      minMessage = "Le nom d'un Nom Matche doit comporter au plus {{ limit }} caractéres"
     *     )
     */
    private $NomMatche;

    /**
     * @ORM\Column(type="time")
     *  @Assert\NotBlank(message="time is required")
     */
    private $time;

    /**
     * @ORM\ManyToOne(targetEntity=Stade::class, inversedBy="matches")
     */
    private $stade;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image2;



    public function __construct()
    {
        $this->billets = new ArrayCollection();
        $this->evaluations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomArbitre(): ?string
    {
        return $this->NomArbitre;
    }

    public function setNomArbitre(string $NomArbitre): self
    {
        $this->NomArbitre = $NomArbitre;

        return $this;
    }

    public function getTour(): ?string
    {
        return $this->tour;
    }

    public function setTour(string $tour): self
    {
        $this->tour = $tour;

        return $this;
    }

    public function getIdStade(): ?int
    {
        return $this->IdStade;
    }

    public function setIdStade(int $IdStade): self
    {
        $this->IdStade = $IdStade;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|Billet[]
     */
    public function getBillets(): Collection
    {
        return $this->billets;
    }

    public function addBillet(Billet $billet): self
    {
        if (!$this->billets->contains($billet)) {
            $this->billets[] = $billet;
            $billet->setMatche($this);
        }

        return $this;
    }

    public function removeBillet(Billet $billet): self
    {
        if ($this->billets->removeElement($billet)) {
            // set the owning side to null (unless already changed)
            if ($billet->getMatche() === $this) {
                $billet->setMatche(null);
            }
        }

        return $this;
    }

    public function getNomMatche(): ?string
    {
        return $this->NomMatche;
    }

    public function setNomMatche(string $NomMatche): self
    {
        $this->NomMatche = $NomMatche;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getStade(): ?Stade
    {
        return $this->stade;
    }

    public function setStade(?Stade $stade): self
    {
        $this->stade = $stade;

        return $this;
    }

    public function getImage1(): ?string
    {
        return $this->image1;
    }

    public function setImage1(?string $image1): self
    {
        $this->image1 = $image1;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }





}

src/Form/MatcheType.php
<?php

namespace App\Form;

use App\Entity\Matche;
use App\Entity\Stade;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatcheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('NomArbitre')
            ->add('tour')
            ->add('date')
            ->add('time')
            ->add('stade' , EntityType::class, [
                'class'=>Stade::class,
                'choice_label'=>'nom'
            ])
            ->add('NomMatche')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Matche::class,
        ]);
    }
}

src/Controller/MatcheController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Entity\Matche;
use App\Entity\Reclamation;
use App\Form\AvisType;
use App\Form\MatcheType;
use App\Repository\BilletRepository;
use App\Repository\MatcheRepository;
use App\Repository\StadeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

class MatcheController extends AbstractController
{
    /**
     * @Route("/matche", name="matche")
     */
    public function index(): Response
    {
        return $this->render('matche/index.html.twig', [
            'controller_name' => 'MatcheController',
        ]);
    }
//Route d'annotation
//Response correspond a la reponse retournée par le controleur
// render methode de retourner une interface
/**
 * @param MatcheRepository $repository
 * @return Response
 * @route("/AfficheM", name="AfficheMatche")
 */
public function Affiche(MatcheRepository $repository){
    $matche=$repository->findAll(); //retourner toutes les objets
    return $this->render('matche/Affiche.html.twig',
        ['matche'=>$matche]);
}
    /**
     * @param MatcheRepository $repository
     * @return Response
     * @route("/AfficheUnM", name="AfficheUnMatche")
     */
    public function Afficheunmatche(MatcheRepository $repository,Request $request){
        $avis = new Avis();
        $form=$this->createForm(AvisType::class,$avis);
        $matche=$repository->findAll();
        $form->handleRequest($request);
        if($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($avis);
            $em->flush();
            $this->addFlash(
                'info',
                'Merci pour votre avis'
            );
            return $this->redirectToRoute('AfficheUnMatche');
        }
        return $this->render('matche/AfficherUnMatch.html.twig',
            ['matche'=>$matche,'form'=>$form->createView()]);
    }
    /**
     * @param MatcheRepository $repository
     * @return Response
     * @route("/ListeM", name="ListeM", methods={"GET"})
     */
    public function ListeM(MatcheRepository $repository): Response
    {    // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        $matche=$repository->findAll(); //retourner toutes les objets


        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('matche/ListeM.html.twig',
            ['matche'=>$matche]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);



    }
//repository- l'entité
//Manger- base
/**
 * @route("/deleteMatche/{id}",name="deleteMatche")
 */
function Delete_matche($id,MatcheRepository $repository){
    $matche=$repository->find($id);
    $em=$this->getDoctrine()->getManager();
    $em->remove($matche);
    $em->flush(); //
    $this->addFlash(
        'info',
        'Deleted Successfully'
    );
    return $this->redirectToRoute('AfficheMatche');
}

/**
 * @param Request $request
 * @return Response
 * @route("matche/ajouter")
 */
function Ajouter_matche(Request $request){
    $matche = new Matche();
    $form=$this->createForm(MatcheType::class,$matche);
    $form->add('ajouter',SubmitType::class);
    $form->handleRequest($request);
    if($form->isSubmitted() && $form->isValid()){
        $date= new \DateTime('now');
        $datematch=$matche->getDate();
        $nbJours =$datematch->diff($date)->days;
        if($nbJours >= 1 && $datematch > $date) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($matche);
            $em->flush();
            $this->addFlash(
                'info',
                'Added Successfully'
            );
            return $this->redirectToRoute('AfficheMatche');
        }
        $erreur="Changer la date ";
        return $this->render('matche/AjouterErreur.html.twig',[
            'form'=>$form->createView(),
            'error'=>$erreur,
            'nbjours'=>$nbJours,
            'date'=>$date,
            'datematch'=>$datematch,
        ]);

    }
    return $this->render('matche/Ajouter.html.twig',[
        'form'=>$form->createView()
    ]);
}
/**
 * @route ("updatematch/{id}",name="modifierMatche")
 */
function Update(MatcheRepository  $repository,$id,Request $request){
    $matche=$repository->find($id);
    $form=$this->createForm(MatcheType::class,$matche);
    $form->add('Update',SubmitType::class);
    $form->handleRequest($request);                                                                                            //pour envoyer la requete
    if ($form->isSubmitted() && $form->isValid()){
        //si la requete tsabet
        $date= new \DateTime('now');
        $datematch=$matche->getDate();
        $nbJours =$datematch->diff($date)->days;
        if($nbJours >= 1 && $datematch > $date) {
        $em=$this->getDoctrine()->getManager();
        $em->flush();
        $this->addFlash(
            'info',
            'Updated Successfully'
        );
        return $this->redirectToRoute("AfficheMatche");
    }
        $erreur="Changer la date ";
        return $this->render('matche/UpdateErreur.html.twig',[
            'form'=>$form->createView(),
            'error'=>$erreur,
            'nbjours'=>$nbJours,
            'date'=>$date,
            'datematch'=>$datematch,
        ]);

    }
    return $this->render('matche/Update.html.twig',[
        'form'=>$form->createView()    //pour afficher les champs de la forme type
    ]);
}
    /**
     * @Route("/ListByMatche/{id}", name="ListByMatche", methods={"GET"})
     */
    function ListBilletByMatche(MatcheRepository $repoM, BilletRepository $repoB, $id){
        $matche=$repoM->find($id);
        $billet=$repoB->ListBilletByMatche($matche->getId());
        return $this->render("matche/Show.html.twig", [
            'a'=>$matche, 'billet'=>$billet
        ]);

    }


    /**
     * @Route("/AffMatcheAjax", name="AffMatchAjax", methods={"POST"})
     */
    public function AffAjaxMatch(Request $request)
    {
        $em = $this->getDoctrine()->getManager();


        $entities =  $em->getRepository(Matche::class)->findAll();

        if(!$entities) {
            $result['entities']['error'] = "Aucun matche trouvée";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }

        return new Response(json_encode($result));
    }

    /**
     * @Route("/RechercheMatche", name="rechMatch", methods={"POST"})
     */
    public function RechercheAjaxMatch(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $entities =  $em->getRepository(Matche::class)->Recherche($requestString);

        if(!$entities) {
            $result['entities']['error'] = "Aucun matche trouvée";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }

        return new Response(json_encode($result));
    }

    /**
     * @Route("/RechercheMatcheDate", name="rechMatchDate", methods={"POST"})
     */
    public function RechercheAjaxMatchDate(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $entities =  $em->getRepository(Matche::class)->RechercheDate($requestString);

        if(!$entities) {
            $result['entities']['error'] = "Aucun matche trouvée";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }

        return new Response(json_encode($result));
    }

    public function getRealEntities($matches){

        foreach ($matches as $m){

            $realEntities[$m->getId()] = [$m->getNomMatche(),$m->getDate()->format('d'),$m->getDate()->format('m'),$m->getDate()->format('y'),$m->getTime()->format('h'),$m->getNomArbitre(),$m->getStade()->getNom(),$m->getImage1(),$m->getImage2(),];
        }

        return $realEntities;
    }
}

templates/matche/AfficherUnMatch.html.twig
{% extends 'base-front.html.twig' %}
{% block content %}

    <div class=innerbannerwrap>
        <div class=content></div>
        <div class=innerbanner><h2 class=bannerHeadline><span>Match</span></h2></div>
    </div>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Donnez votre Avis
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Votre Avis</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ form_start(form) }}
                        <div class="cp-field">
                            <h5>Note</h5>
                            <div class="form-group">
                                {{ form_widget(form.note) }}
                            </div>
                        </div>
                        <div class="cp-field">
                            <h5>Votre Avis</h5>
                            <div class="form-group">
                                {{ form_widget(form.description) }}
                            </div>
                        </div>
                        <div class="save-stngs pd3">
                            <ul>
                                <!--<li><button type="submit">Envoyer</button></li>-->
                                <li> {{ form_widget(form.Envoyer) }}</li>
                            </ul>
                        </div>
                        {{ form_end(form) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>


    {% endfor %}

    <section class=innerpage_all_wrap>

        <div class=container>
            <div class=row>
                <h2 class=heading>
                    match <span>Coupe du Monde Qatar 2022™ </span>
                </h2>
                <div class="bg-red shop_select clearfix">
                    <div class="select_shopping">
                        <form>
                            <div class="form-group">
                                <label class="headline01">Sort by match</label>
                                <select class="form-control" id="match">
                                    {% for m in matche %}
                                    <option value="{{m.NomMatche}}">{{m.NomMatche}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="headline01">Date</label>
                                <input type="date" id="datem" class="form-control">

                            </div>

                        </form>
                    </div>
                </div>
                <div id="result">

                </div>

            </div>
        </div>
    </section>

    <script type=text/javascript>
        $(function () {
            $('#da_gallery .gallery-list ').hoverdir();
        });
    </script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            var searchRequest = null;
            $("#match").change(function() {
                var minlength = 0;
                var that = this;
                var value = $(this).val();
                var entitySelector = $("#result").html('');
                if (searchRequest != null)
                    searchRequest.abort();
                searchRequest = $.ajax({
                    type: "POST",
                    url: "{{ path('rechMatch') }}",
                    data: {
                        'q' : value
                    },
                    dataType: "text",
                    success: function(msg){
                        console.log(msg);
                        var result = JSON.parse(msg);
                        $.each(result, function(key, arr) {
                            $.each(arr, function(id, value) {
                                if (key === 'entities') {
                                    if (id !== 'error') {
                                        var img1={{ asset('upload/') }}+value[7];
                                        var img2={{ asset('upload/')  }}+value[8];
                                        entitySelector.append(
                                        '<div class="matchSchedule_details row"> <div class="match_next right-triangle"> <div class="wrap_match_next right-triangle"><div class=right-padding><h4 class=headline03>'+value[0]+ '</h4>'+
                                            '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div>'+
                                        '</div></div>'+
                                        '<div class=match_versus><div class="bg-blackimg match_versus02"><div class=nextmatchDetails><div class="wrap-logo clearfix">'+
                                            '<div class=logo-match><img src="'+img1+'" alt=image></div>'+
                                            '<div class=match_vs>vs</div>'+
                                            '<div class=logo-match><img src="'+img2+'" alt=image></div>'+
                                            '</div>'+
                                            '<p class=match_dtls><b> Date :</b>'+value[1]+'/'+value[2]+'/'+value[3]+'</p>'+
                                        '<p class=match_dtls><b> Time :</b>'+value[4]+ 'PM</p>'+
                                        '<p class=match_dtls><b> Nom Arbitre Principal :</b>'+value[5]+'</p>'+
                                        '<p class=match_dtls><b> Stade :</b>'+value[6]+'<br> <li><a href="ListByMatche/'+id+'" class="btn-small01 btn-green">Billet</a></li></p></div>'+
                                        '</div></div></div>'
                                        );
                                    } else {
                                        entitySelector.append('<div class="error">'+value+'</div>');
                                    }
                                }
                            });
                        });
                    }
                });
            });
        });
    </script>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            var searchRequest = null;
            $("#datem").change(function() {
                console.log($(this).val())
                var minlength = 0;
                var that = this;
                var value = $(this).val();
                var entitySelector = $("#result").html('');
                if (searchRequest != null)
                    searchRequest.abort();
                searchRequest = $.ajax({
                    type: "POST",
                    url: "{{ path('rechMatchDate') }}",
                    data: {
                        'q' : value
                    },
                    dataType: "text",
                    success: function(msg){
                        console.log(msg);
                        var result = JSON.parse(msg);
                        $.each(result, function(key, arr) {
                            $.each(arr, function(id, value) {
                                if (key === 'entities') {
                                    if (id !== 'error') {
                                        var img1={{ asset('upload/') }}+value[7];
                                        var img2={{ asset('upload/')  }}+value[8];
                                        entitySelector.append(
                                            '<div class="matchSchedule_details row"> <div class="match_next right-triangle"> <div class="wrap_match_next right-triangle"><div class=right-padding><h4 class=headline03>'+value[0]+ '</h4>'+
                                            '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div>'+
                                            '</div></div>'+
                                            '<div class=match_versus><div class="bg-blackimg match_versus02"><div class=nextmatchDetails><div class="wrap-logo clearfix">'+
                                            '<div class=logo-match><img src="'+img1+'" alt=image></div>'+
                                            '<div class=match_vs>vs</div>'+
                                            '<div class=logo-match><img src="'+img2+'" alt=image></div>'+
                                            '</div>'+
                                            '<p class=match_dtls><b> Date :</b>'+value[1]+'/'+value[2]+'/'+value[3]+'</p>'+
                                            '<p class=match_dtls><b> Time :</b>'+value[4]+ 'PM</p>'+
                                            '<p class=match_dtls><b> Nom Arbitre Principal :</b>'+value[5]+'</p>'+
                                            '<p class=match_dtls><b> Stade :</b>'+value[6]+'<br> <li><a href="ListByMatche/'+id+'" class="btn-small01 btn-green">Billet</a></li></p></div>'+
                                            '</div></div></div>'
                                        );
                                    } else {
                                        entitySelector.append('<div class="error">'+value+'</div>');
                                    }
                                }
                            });
                        });
                    }
                });
            });
        });
    </script>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            var searchRequest = null;

                var entitySelector = $("#result").html('');
                if (searchRequest != null)
                    searchRequest.abort();
                searchRequest = $.ajax({
                    type: "POST",
                    url: "{{ path('AffMatchAjax') }}",
                    data: {
                        'q' : 0
                    },
                    dataType: "text",
                    success: function(msg){
                        console.log(msg);
                        var result = JSON.parse(msg);
                        $.each(result, function(key, arr) {
                            $.each(arr, function(id, value) {
                                if (key === 'entities') {
                                    if (id !== 'error') {
                                        var img1={{ asset('upload/') }}+value[7];
                                        var img2={{ asset('upload/')  }}+value[8];
                                        entitySelector.append(
                                            '<div class="matchSchedule_details row"> <div class="match_next right-triangle"> <div class="wrap_match_next right-triangle"><div class=right-padding><h4 class=headline03>'+value[0]+ '</h4>'+
                                            '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div>'+
                                            '</div></div>'+
                                            '<div class=match_versus><div class="bg-blackimg match_versus02"><div class=nextmatchDetails><div class="wrap-logo clearfix">'+
                                            '<div class=logo-match><img src="'+img1+'" alt=image></div>'+
                                            '<div class=match_vs>vs</div>'+
                                            '<div class=logo-match><img src="'+img2+'" alt=image></div>'+
                                            '</div>'+
                                            '<p class=match_dtls><b> Date :</b>'+value[1]+'/'+value[2]+'/'+value[3]+'</p>'+
                                            '<p class=match_dtls><b> Time :</b>'+value[4]+ 'PM</p>'+
                                            '<p class=match_dtls><b> Nom Arbitre Principal :</b>'+value[5]+'</p>'+
                                            '<p class=match_dtls><b> Stade :</b>'+value[6]+'<br> <li><a href="ListByMatche/'+id+'" class="btn-small01 btn-green">Billet</a></li></p></div>'+
                                            '</div></div></div>'
                                        );
                                    } else {
                                        entitySelector.append('<div class="error">'+value+'</div>');
                                    }
                                }
                            });
                        });
                    }
                });

        });
    </script>

{% endblock %}

templates/matche/ListeM.html.twig
{% block content %}
    <img src="{{ asset ('public/back-office/logo.jpg')}}" alt="" height="58">

   <h1 align="center">Liste Des Matchs </h1> <hr>


                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                        <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>NomMatche</th>
                            <th>NomArbitre</th>
                            <th>Stade</th>
                            <th>Date</th>
                            <th>Tour</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr {% for m in matche %}>
                            <td>{{ m.id }}</td>
                            <td>{{ m.NomMatche }}</td>
                            <td>{{ m.NomArbitre }}</td>
                            <td>{{ m.stade.nom }}</td>
                            <td>{{ m.date|date('d-m-Y') }}</td>
                            <td>{{ m.tour }}</td>

                        </tr {% endfor %}>
                        </tbody>
                    </table>

    <script>
        $('#datatable-buttons').DataTable()
    </script>
{% endblock %}